# Generated by Django 5.2.5 on 2025-10-12 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('meaning', models.TextField()),
                ('region', models.CharField(blank=True, max_length=120)),
                ('register', models.CharField(choices=[('neutral', 'Neutral'), ('informal', 'Informal'), ('slang', 'Slang'), ('formal', 'Formal')], default='neutral', max_length=20)),
                ('usage_notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['text'],
                'unique_together': {('owner', 'text')},
            },
        ),
    ]
